# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-s3-website
  description: Terraform Module for Creating S3 backed Websites and Route53 DNS
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, s3, s3-website, route53, hcl2



